### ISSUE TITLE
Hook up Travis-CI

### ISSUE THREAD

**Issue by jgable** [nandub/hubot-irc#89]
Add a `.travis.yml` to prevent issues like #88 .

``` yml
language: node_js
node_js:
  - "0.11"
  - "0.10"
git:
  submodules: false
before_script:
  - npm install -g grunt-cli
```

Update `package.json` to use `grunt validate` for test.
